clothes = {
    "sneakers":{
        "35-40":"1",
        "41-45":"2",
        "46>":"3"
    },
    "shoes":{
        "35-40":"4",
        "41-45":"5",
        "46>":"6"
    },
    "t_shorts":{
        "easy":"7", 
        "hard":"8"
    },
    "shorts":{
        "djeans":"9",
        "sport":"10"
    },
    "hudy":{
        "over":"11",
        "normal":"12"
    },
    "puh":{
        "spring":"13",
        "winter":"14"
    },
    "bags":{
        "big":"15",
        "small":"16"
    }
}       